print("------------------------------------------------")
print("Tuinui Bar & Restaurant")
print("------------------------------------------------")
print("Tom Yum Kung             x 1  : 150 Baht")
print("Chicken Coconut Soup     x 1  : 100 Baht")
print("Omlet                    x 2  : 70 Baht")
print("Chicken Massaman         x 1  : 50 Baht")
print("Pepsi                    x 1  : 30 Baht")
print("Beer                     x 3  : 220 Baht")
print("Coke                     x 2  : 30 Baht")
print("Fruit Smoothie           x 1  : 50 Baht")
print("------------------------------------------------")
print("Total : 700 Baht")